name: alodjinha_app
description: Samuel Arna test
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  bloc_pattern: ^2.5.1
  carousel_slider: ^1.3.0
  http: ^0.12.0+4
  intl: ^0.16.1
  lazy_loading_list: ^1.0.0+1
  flutter_html: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf    
  uses-material-design: true
